"""Fixed UserChannel

Revision ID: 65815126fb12
Revises: 9fa8f2d40b8b
Create Date: 2025-05-06 19:23:58.514769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65815126fb12'
down_revision: Union[str, None] = '9fa8f2d40b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_channels', sa.Column('min_reactions', sa.Integer(), nullable=True))
    op.add_column('user_channels', sa.Column('max_reactions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_channels', 'max_reactions')
    op.drop_column('user_channels', 'min_reactions')
    # ### end Alembic commands ###
