"""Added views label to Channel 2

Revision ID: 6b926aec2482
Revises: 52b9d7b013c7
Create Date: 2025-05-16 14:01:10.320461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b926aec2482'
down_revision: Union[str, None] = '52b9d7b013c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_channels', sa.Column('views', sa.Integer(), nullable=True))
    op.drop_column('user_channels', 'view')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_channels', sa.Column('view', sa.INTEGER(), nullable=True))
    op.drop_column('user_channels', 'views')
    # ### end Alembic commands ###
